controller_list:
  - name: /mhuman/right_arm_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - jright_shoulder_rotz
      - jright_shoulder_roty
      - jright_shoulder_rotx
      - jright_forearm_rotz
      - jright_forearm_roty
      - jright_wrist_roty
      - jright_wrist_rotx

  - name: /mhuman/right_gripper_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - jright_grip_rhand
      
  - name: /mhuman/left_arm_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - jleft_shoulder_rotz
      - jleft_shoulder_roty
      - jleft_shoulder_rotx
      - jleft_forearm_rotz
      - jleft_forearm_roty
      - jleft_wrist_roty
      - jleft_wrist_rotx

  - name: /mhuman/left_gripper_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - jright_grip_lhand
      
